version: '3.3'
services:
  application:
    image: cloud_run_example
    container_name: cloud_run_example
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/cloud_run_example_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:10.3
    container_name: cloud_run_example-postgres
    environment:
      - POSTGRES_DB=cloud_run_example_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - cloud_run_example_psql:/var/lib/postgresql/data
volumes:
  cloud_run_example_psql:
