use Mix.Config

# We also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :cloud_run_example, CloudRunExampleWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  root: ".",
  server: true

# Do not print debug messages in production
config :logger, level: :info
